### PR TITLE
Proposal to describe additional dimensions in extent

### PR DESCRIPTION
**Pull request by jerstlouis**

### CODE REVIEW

**Comment by Schpidi** [comment]
thanks @jerstlouis! do you think we could base this on the extent element from common using $ref instead of copying the content just like in collectionInfo (https://github.com/Schpidi/ogcapi-coverages-1/blob/master/yaml-unresolved/schemas/ogcapi-coverages-1_1.0/collectionInfo.yaml#L2)?

**Comment by jerstlouis** [comment]
Sure other than tweaking the description at the top the first part is copied from common ( https://github.com/opengeospatial/oapi_common/blob/master/collections/openapi/schemas/extent.yaml ).

I am not sure how to do that though.

**Comment by Schpidi** [comment]
I tried it in https://github.com/Schpidi/ogcapi-coverages-1/commit/80d815ac43c5811157ba5e897cf831102d909cdc

The spectral linter is happy.

Note that I added the `axisLabel` property which I believe we need in order to make it explicit which axis is used in case the `rs` has multiple ones.

**Comment by jerstlouis** [comment]
@Schpidi Would that be different from `name`?

**Comment by Schpidi** [comment]
good point. I guess it depends how we write the corresponding requirement. But rather than removing axisLabel I'd propose to remove name.

**Pull request merged**
